#!/usr/bin/env python3
"""
Crop name mapping for the pre-pipeline normalizer.

crop_mapping: {raw_variant: canonical_name}
  - Keys are the original crop name strings as they appear in the raw CSV.
  - Values are the canonical primary crop names used throughout the pipeline.

To add more crops, append entries here — crop_normalizer.py picks them up automatically.
"""

crop_mapping = {
    # Paddy & Wheat
    "Paddy Dhan": "Paddy",
    "Paddy (Dhan)": "Paddy",
    "Wheat": "Wheat",
    
    # Cotton & Sugarcane
    "Cotton Kapas": "Cotton",
    "Cotton (Kapas)": "Cotton",
    "Sugarcane Noble Cane": "Sugarcane",
    "Sugarcane (Noble Cane)": "Sugarcane",
    "Sugar Beet": "Sugar Beet",
    
    # Pulses & Beans
    "Bengal Gram GramChick PeaKabuliChana": "Bengal Gram",
    "Bengal Gram (Gram/Chick Pea/Kabuli/Chana)": "Bengal Gram",
    "Black Gram urd bean": "Black Gram",
    "Black Gram (urd bean)": "Black Gram",
    "Green Gram Moong Bean Moong": "Green Gram",
    "Green Gram (Moong Bean/ Moong)": "Green Gram",
    "Pigeon pea red gramarhartur": "Pigeon Pea",
    "Pigeon pea (red gram/arhar/tur)": "Pigeon Pea",
    "Lentil Masur": "Lentil",
    "Lentil (Masur)": "Lentil",
    "Moth Bean kidney bean deww gram": "Bean",
    "Moth Bean (kidney bean/ deww gram)": "Bean",
    "Horse Gram kulthikultha": "Horse Gram",
    "Horse Gram (kulthi/kultha)": "Horse Gram",
    "Cowpea Vegetable": "Cowpea",
    "Cowpea (Vegetable)": "Cowpea",
    "lobia": "Cowpea",
    "Rajma french bean": "Bean",
    "Rajma (french bean)": "Bean",
    "Rajmash Bean": "Bean",
    "Ricebean": "bean",
    "Cluster Bean": "Bean",
    "French Bean": "Bean",
    "Broad Bean": "Bean",
    "Faba Bean Horse Beanwindsor Bean": "Bean",
    "Faba Bean (Horse Bean/windsor Bean)": "Bean",
    "Lab Lab": "Bean",
    "Mochai lab-lab": "Bean",
    "Mochai (lab-lab)": "Bean",
    "Indian Bean Vegetable": "Bean",
    "Indian Bean (Vegetable)": "Bean",
    "Dolichos Bean": "Bean",
    "Winged Bean": "Bean",
    "Runner Bean": "Bean",
    "Yard Long Bean": "Bean",
    "Khesari chickling vetch grass pea": "Lathyrus",
    "Khesari (chickling vetch/ grass pea)": "Lathyrus",
    "Lethyrus": "Lathyrus",

    # Grains & Millets
    "Maize Makka": "Maize",
    "Maize (Makka)": "Maize",
    "fodder maize": "Maize",
    "Baby Corn": "Maize",
    "Pearl Millet BajraBulrush MilletSpiked Millet": "Pearl Millet",
    "Pearl Millet (Bajra/Bulrush Millet/Spiked Millet)": "Pearl Millet",
    "Sorghum JowarGreat Millet": "Sorghum",
    "Sorghum (Jowar/Great Millet)": "Sorghum",
    "fodder sorghum": "Fodder Sorghum",
    "FingerMillet RagiMandika": "Finger Millet",
    "FingerMillet (Ragi/Mandika)": "Finger Millet",
    "Barnyard Millet KundiraivlliSawan": "Barnyard Millet",
    "Barnyard Millet (Kundiraivlli/Sawan": "Barnyard Millet",
    "Italian Millet ThenaiNavaneFoxtail MilletKang": "Foxtail Millet",
    "Italian Millet (Thenai/Navane/Foxtail Millet/Kang)": "Foxtail Millet",
    "Kodo Millet KodaraVaragu": "Kodo Millet",
    "Kodo Millet (Kodara/Varagu)": "Kodo Millet",
    "Common Millet PanivaraguChenaProso MilletHogm": "Proso Millet",
    "Common Millet (Panivaragu/Chena/Proso Millet/Hogm": "Proso Millet",
    "Little Millet SamaiKutkikodo-kutki": "Little Millet",
    "Little Millet (Samai/Kutki/kodo-kutki)": "Little Millet",
    "Barley Jau": "Barley",
    "Barley (Jau)": "Barley",
    "Oats": "Oats",
    "Triticale": "Triticale",
    "Buck Wheat Kaspat": "Buckwheat",
    "Buck Wheat (Kaspat)": "Buckwheat",

    # Oilseeds
    "Mustard": "Mustard",
    "Indian rapeseed and mustard yellow sarson": "Mustard",
    "Indian rapeseed and mustard (yellow sarson)": "Mustard",
    "Raya Indian Mustard": "Mustard",
    "Raya (Indian Mustard)": "Mustard",
    "African Sarson": "Mustard",
    "Brown Sarson": "Mustard",
    "Gobhi Sarson": "Mustard",
    "Toria": "Mustard",
    "Groundnut pea nutmung phalli": "Groundnut",
    "Groundnut (pea nut/mung phalli)": "Groundnut",
    "Soybean bhat": "Soybean",
    "Soybean (bhat)": "Soybean",
    "Sesame GingellyTilSesamum": "Sesame",
    "Sesame (Gingelly/Til)/Sesamum": "Sesame",
    "Castor Rehri Rendi Arandi": "Castor",
    "Castor (Rehri, Rendi, Arandi)": "Castor",
    "Sunflower suryamukhi": "Sunflower",
    "Sunflower (suryamukhi)": "Sunflower",
    "Linseed alsi": "Linseed",
    "Linseed (alsi)": "Linseed",
    "Safflower kusumkardi": "Safflower",
    "Safflower (kusum/kardi)": "Safflower",
    "Niger Ramtil": "Niger",
    "Niger (Ramtil)": "Niger",
    "Oil palm": "Oil Palm",

    # Vegetables (Gourds & Melons)
    "Bottle Gourd": "Bottle Gourd",
    "Bitter Gourd": "Bitter Gourd",
    "Pointed Gourd": "Pointed Gourd",
    "Ridge Gourd": "Ridge Gourd",
    "Snake Gourd": "Snake Gourd",
    "Sponge Gourd": "Sponge Gourd",
    "Ivy Gourd": "Ivy Gourd",
    "Kundru": "Ivy Gourd",
    "Ash Gourd Petha": "Ash Gourd",
    "Ash Gourd (Petha)": "Ash Gourd",
    "Ribbed Gourd Kali Tori": "Ribbed Gourd",
    "Ribbed Gourd (Kali Tori)": "Ribbed Gourd",
    "Spine Gourd": "Spine Gourd",
    "Cucumber": "Cucumber",
    "Musk Melon": "Muskmelon",
    "Watermelon": "Watermelon",
    "Snap Melon": "Snap Melon",
    "Indian Squash TindaRound Melon": "Round Melon",
    "Indian Squash (Tinda/Round Melon)": "Round Melon",
    "Long Melon": "Long Melon",
    "Pumpkin": "Pumpkin",
    "Chapan Kaddu": "Chapan Kaddu",
    "Summer Squash Vegetable Marrow": "Summer Squash",
    "Summer Squash (Vegetable Marrow)": "Summer Squash",
    "Bush Squash": "Bush Squash",
    "Melon": "Melon",
    "Smooth Guard": "Sponge Gourd",

    # Vegetables (General)
    "BhindiOkraLadysfinger": "Okra",
    "Bhindi(Okra/Ladysfinger)": "Okra",
    "Tomato": "Tomato",
    "Potato": "Potato",
    "Onion": "Onion",
    "Brinjal": "Brinjal",
    "Cauliflower": "Cauliflower",
    "Cabbage": "Cabbage",
    "Chinese Cabbage": "Chinese Cabbage",
    "Broccoli": "Broccoli",
    "Brussils Sprouts": "Brussels Sprouts",
    "Capsicum": "Capsicum",
    "Chillies": "Chillies",
    "Bell Pepper": "Chillies",
    "Pepper": "Pepper",
    "Carrot": "Carrot",
    "Radish": "Radish",
    "Turnip Saljam": "Turnip",
    "Turnip (Saljam)": "Turnip",
    "Pea Vegetable": "Pea",
    "Pea (Vegetable)": "Pea",
    "Peas field peas garden peasmatar": "Pea",
    "Peas (field peas/ garden peas/matar)": "Pea",
    "Garden Pea": "Garden Pea",
    "Butter Pea Vegetable": "Butter Pea",
    "Butter Pea (Vegetable)": "Butter Pea",
    "Drum Stick": "Drumstick",
    "Spinach Palak": "Spinach",
    "Spinach (Palak)": "Spinach",
    "Leafy Vegetable": "Leafy Vegetable",
    "Lettuce": "Lettuce",
    "Knol-Khol": "Knol-Khol",
    "AmaranthusGrain Amaranthus": "Amaranthus",
    "Amaranthus/Grain Amaranthus": "Amaranthus",
    "Beet Root Garden BeetStock Beet": "Beetroot",
    "Beet Root (Garden Beet/Stock Beet)": "Beetroot",
    "Colocasia Arvi Arbi": "Colocasia",
    "Colocasia (Arvi, Arbi)": "Colocasia",
    "Amarphophallus SurankandElephant Foot Yam": "Elephant Foot Yam",
    "Amarphophallus (Surankand/Elephant Foot Yam)": "Elephant Foot Yam",
    "ARUM": "Arum",
    "White Yam": "White Yam",
    "Greater Yam": "Greater Yam",
    "Lesser Yam Rafula": "Lesser Yam",
    "Lesser Yam (Rafula)": "Lesser Yam",
    "Sweet Potato": "Sweet Potato",
    "Tapioca Cassava": "Tapioca",
    "Tapioca (Cassava)": "Tapioca",

    # Spices & Herbs
    "Turmeric": "Turmeric",
    "Ginger": "Ginger",
    "Garlic": "Garlic",
    "Coriander": "Coriander",
    "Cumin": "Cumin",
    "Fennel": "Fennel",
    "Fenugreek": "Fenugreek",
    "Methi Fenugreek": "Fenugreek",
    "Methi (Fenugreek)": "Fenugreek",
    "Cardamom": "Cardamom",
    "Large Cardamom": "Large Cardamom",
    "Clove": "Clove",
    "Cinnamon": "Cinnamon",
    "Curry Leaf": "Curry Leaf",
    "Mint": "Mint",
    "Mentha": "Mint",
    "Bishops Weed": "Bishop's Weed",
    "Dill Seed": "Dill Seed",
    "Saffron": "Saffron",
    "Vanilla": "Vanilla",
    "Bay Leaf": "Bay Leaf",
    "Celery": "Celery",
    "Nutmeg": "Nutmeg",

    # Fruits
    "Mango": "Mango",
    "Banana": "Banana",
    "Citrus": "Citrus",
    "Acid Lime": "Acid Lime",
    "Lemon": "Lemon",
    "Mosambi": "Mosambi",
    "Orange": "Orange",
    "Guava": "Guava",
    "Papaya": "Papaya",
    "Pomegranate": "Pomegranate",
    "Apple": "Apple",
    "Grape": "Grape",
    "Litchi": "Litchi",
    "Sapota": "Sapota",
    "Jack Fruit": "Jackfruit",
    "Aonla": "Aonla",
    "Ber": "Ber",
    "Jamun": "Jamun",
    "Coconut": "Coconut",
    "Arecanut": "Arecanut",
    "Cashew": "Cashew",
    "Walnut": "Walnut",
    "Almond": "Almond",
    "Pecan nut": "Pecan Nut",
    "Chestnut": "Chestnut",
    "Custard Apple": "Custard Apple",
    "Pineapple": "Pineapple",
    "Strawberry": "Strawberry",
    "Peach": "Peach",
    "Pear": "Pear",
    "Plum": "Plum",
    "Apricot": "Apricot",
    "Fig": "Fig",
    "Kiwi Fruit": "Kiwi Fruit",
    "Avacado": "Avocado",
    "Loquat": "Loquat",
    "Passion Fruit": "Passion Fruit",
    "Sweet Cherry": "Sweet Cherry",
    "Persimmon": "Persimmon",
    "Kokum": "Kokum",
    "Bail": "Bael",
    "Lahsoda": "Gunda",
    "Koronda": "Karonda",
    "Palmyra": "Palmyra",
    "Lehberry": "Lehberry",
    "Mulberry": "Mulberry",
    "Olive": "Olive",

    # Commercial, Fibers & Plantation
    "Tobacco": "Tobacco",
    "Jute": "Jute",
    "Patua": "Jute",
    "Sunnhemp Patua": "Sunnhemp",
    "Sunnhemp (Patua)": "Sunnhemp",
    "Roselle Mesta": "Roselle",
    "Roselle (Mesta)": "Roselle",
    "Mesta": "Mesta",
    "Rubber": "Rubber",
    "Tea": "Tea",
    "Coffee": "Coffee",
    "Cocoa": "Cocoa",
    "OPIUM POPY": "Opium Poppy",
    "Bhang Hemp Canabis": "Hemp",
    "Bhang (Hemp, Canabis)": "Hemp",
    "Betel Vine": "Betel Vine",
    "Jojoba": "Jojoba",
    "Jatropha Ratanjot": "Jatropha",
    "Jatropha (Ratanjot)": "Jatropha",
    "Tumba": "Tumba",

    # Flowers
    "Rose": "Rose",
    "Marigold": "Marigold",
    "Jasmine": "Jasmine",
    "Gladiolus": "Gladiolus",
    "Chrysanthemum": "Chrysanthemum",
    "Tuberose": "Tuberose",
    "Hibiscus Gurhal": "Hibiscus",
    "Hibiscus (Gurhal)": "Hibiscus",
    "Gerbera": "Gerbera",
    "Carnation": "Carnation",
    "China Astor": "China Aster",
    "Anthurium": "Anthurium",
    "Lilliums": "Lilies",
    "Cymbidium": "Cymbidium",
    "Zentedeschia": "Zantedeschia",
    "Crossandra": "Crossandra",
    "Periwinkle": "Periwinkle",
    "Kaner": "Oleander",
    "Caleus": "Coleus",

    # Fodder & Grasses
    "Barseem": "Berseem",
    "Lucerne Alfalfa": "Lucerne",
    "Lucerne (Alfalfa)": "Lucerne",
    "Napier Grass": "Napier Grass",
    "BAJRA NAPIER HYBRID": "Napier Grass",
    "Buffel Grass Anjan Grass": "Buffel Grass",
    "Buffel Grass (Anjan Grass)": "Buffel Grass",
    "Anjan Grass": "Buffel Grass",
    "Sudan Grass": "Sudan Grass",
    "Guinea Grass": "Guinea Grass",
    "Sen Grass": "Sen Grass",
    "Setaria Grass": "Setaria Grass",
    "Tall Fescue Grass": "Tall Fescue Grass",
    "Ryegrass": "Ryegrass",
    "Marvel Grass": "Marvel Grass",
    "Dinanath Grass": "Dinanath Grass",
    "Dharaf Grass": "Dharaf Grass",
    "Golden Thimothy": "Golden Timothy",
    "velimasal": "Velimasal",
    "rajka bajri": "Lucerne",
    "rajka bajri.": "Lucerne",
    "Dhaincha": "Dhaincha",
    "Indian Clover Senji Sweet Clover": "Indian Clover",
    "Indian Clover (Senji Sweet Clover)": "Indian Clover",
    "Senji": "Indian Clover",
    "White Clover Shaftal": "White Clover",
    "White Clover (Shaftal)": "White Clover",
    "Red Clover": "Red Clover",
    "Persian Clover": "Persian Clover",
    "Teosinte": "Teosinte",
    "Stylosanthes": "Stylosanthes",
    "Pillipesara": "Pillipesara",
    "Birdwood Grass": "Birdwood Grass",

    # Forestry
    "Teak": "Teak",
    "Sagoan": "Teak",
    "Poplar": "Poplar",
    "Eculeptous": "Eucalyptus",
    "Neem": "Neem",
    "Babool": "Babul",
    "Sandal Wood": "Sandalwood",
    "Sal Wood": "Sal Wood",
    "Chinar Tree": "Chinar Tree",

    # Medicinal & Others
    "Aloe Vera": "Aloe Vera",
    "Tulsi": "Tulsi",
    "Safed Musli": "Safed Musli",
    "Satawar": "Shatavari",
    "Stevia": "Stevia",
    "Mushroom": "Mushroom",
    "Beekeeping": "Beekeeping",
    "Honey plant": "Honey Plant",
    "Karan Rai": "Karan Rai",
    "Guar": "Guar",
    "KolanchiTephrosia Purpurea": "Kolanchi",
    "Kolanchi(Tephrosia Purpurea)": "Kolanchi",
    "Rocket salad taramira": "Rocket Salad",
    "Rocket salad (taramira)": "Rocket Salad",
}


def get_filtered_mapping(primary_crops: list[str]) -> dict[str, str]:
    """
    Returns a {variant: canonical} mapping restricted to the given primary crops.

    Example:
        get_filtered_mapping(["Cotton"]) →
        {"Cotton Kapas": "Cotton", "Cotton (Kapas)": "Cotton"}
    """
    primary_set = {c.strip().lower() for c in primary_crops}
    return {k: v for k, v in crop_mapping.items() if v.strip().lower() in primary_set}


def get_reverse_mapping(primary_crops: list[str]) -> dict[str, list[str]]:
    """
    Returns a {canonical: [all_variants]} mapping for the given primary crops.

    Example:
        get_reverse_mapping(["Cotton"]) →
        {"Cotton": ["Cotton Kapas", "Cotton (Kapas)"]}
    """
    result: dict[str, list[str]] = {}
    primary_set = {c.strip().lower() for c in primary_crops}
    for variant, canonical in crop_mapping.items():
        if canonical.strip().lower() in primary_set:
            result.setdefault(canonical, []).append(variant)
    return result
